version: '3.0'

services:

   db:
        image: mysql
        environment:
            MYSQL_ROOT_PASSWORD: aerobics
            MYSQL_DATABASE: test
        volumes:
            - /opt/mysql_data:/var/lib/mysql
        ports:
            - 3306:3306